### ISSUE TITLE
Source extension isn't respected

### ISSUE THREAD

**Issue by danielroe** [unjs/mkdist#11]
In a directory where there is both `components.d.ts` and `components.mjs` both output files (may) have the contents of `components.mjs`.

Example: https://unpkg.com/browse/@nuxt/component-discovery@0.2.0/dist/runtime/components.tmpl.d.ts

cc: @pi0

**Comment by danielroe** [comment]
Actually I'm in two minds as to whether this is a bug as it's only replicable with `declaration: true` _and_ a custom `.d.ts`  file added in directory to be transpiled; happy to close or add a safety check if we feel that's better. Thoughts @pi0?

**Comment by pi0** [comment]
This seems a bug. If there is already a declaration with same name we have to preserve it
