### ISSUE TITLE
Option to disable transpiling for Vue SFC

### ISSUE THREAD

**Issue by antfu** [unjs/mkdist#14]
In `<script setup lang="ts">`, SFC compiler uses TS definition as the hint for generating runtime props. [example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuZGVmaW5lUHJvcHM8e1xuICBhOiBudW1iZXIsXG4gIGI/OiBzdHJpbmdcbn0+KClcbiAgXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGlucHV0IHYtbW9kZWw9XCJtc2dcIj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSJ9)

Currently, mkdist will always remove the TS annotation make the information lost. I think we should introduce an option to disable the behaviour and probably bypass `<script setup lang="ts">` smartly by default.

**Comment by pi0** [comment]
Bypassing smartly by default seems a nice idea. BTW do you know of any other TS micros other than `defineProps` that need to be preserved?

**Comment by antfu** [comment]
And also `defineEmit`
