### ISSUE TITLE
Sass compilation

### ISSUE THREAD

**Issue by guibulator** [unjs/mkdist#182]
### Environment

Node 18.15.0.
mkdist: latest

### Reproduction

No reproduction

### Describe the bug

As per the documentation in [https://github.com/nuxt/module-builder](https://github.com/nuxt/module-builder), it's mentioned that only js, ts and vue files would be transformed. 
```js
runtime/*: Individually transformed files using [unjs/mkdist](https://github.com/unjs/mkdist)
Javascript and .ts files will be transformed to .mjs with extracted types on .d.ts file with same name
.vue files will be transformed with extracted .d.ts file
-> Other files will be copied as is
```
I have an issue where sass files are transformed to empty css but I would like the scss file to be copied as is. I see from the tests that scss files are compiled: https://github.com/unjs/mkdist/blob/a0d637d75f5f8b541a475e763e2cd839badb4239/test/index.test.ts#L86

Is there a way to opt-out of this and to just copy the file as is?

**Comment by ennioVisco** [comment]
It should have been addressed in `1.3.0`, as it is mentioned in #152, which is mentioned in the release details.
Are you using the latest version of `mkdist`?

**Comment by guibulator** [comment]
I do use the latest version. So based off of the PR you mentioned, I see that the default loaders are now this
https://github.com/wd-4000/mkdist/blob/22515607be5b47b9f065fa41a3fc8ca297b125af/src/loaders/index.ts
```
export const defaultLoaders: LoaderName[] = ["js", "vue", "sass"];
```
We can configure the loaders using the mkdist options.
So from mkdist perspective, it works. But we can't configure the [nuxt ](https://github.com/nuxt/module-builder) it seems and it will take the default which does sass compilation but as per their documentation, it shouldn't try to compile sass.
I guess I will open a ticket in  [nuxt ](https://github.com/nuxt/module-builder then to allow configuring loaders.

**Comment by pi0** [comment]
Hi and sorry for responding late. Let's track it via https://github.com/nuxt/module-builder/issues/90 to allow opting out from this behavior.
