### ISSUE TITLE
Use `vue-tsc` to generate dts for Vue SFC

### ISSUE THREAD

**Issue by antfu** [unjs/mkdist#22]
https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc

**Comment by cpreston321** [comment]
@pi0 - Can I work on this ?

**Comment by pi0** [comment]
Sure. /cc @danielroe If you have some comments to add

**Comment by danielroe** [comment]
That would be great! Feel free to ping me if you have any questions.
