### ISSUE TITLE
Transpilation of vue components with script setup 

### ISSUE THREAD

**Issue by kugatsu765** [unjs/mkdist#24]
Hi, i use your package through (unbuild)[https://github.com/unjs/unbuild]. 

And after a lot of test to translate ts component to js. I'm fail with component who use `scrip setup`.
The component is only copy without transformation. with ts or js component it's ok and the type file is generate. 

Maybe i miss something =)

Have a nice day

<img width="886" alt="Capture d’écran 2022-02-01 à 16 47 55" src="https://user-images.githubusercontent.com/41836255/152001498-73d3839b-67ab-4201-84d8-adf49fe489b8.png">

**Comment by pi0** [comment]
Hi @kugatsu765. It is expected. Since `<script setup>` supports for special ts micros like `defineProps`, we stopped transpiling it. (see https://github.com/unjs/mkdist/issues/14 for more info). Any reason you want ts to be removed from `<script setup>` blocks?

**Comment by kugatsu765** [comment]
Hi, thanks

It was to remove typescript for project who do not use ts. Not the `script setup`. But i will do with the classic way =)

**Comment by pi0** [comment]
vite and nuxt3 setups use esbuild so should be no problem but if you prefer we can have it back with a flag to transpile `<script setup>` :)

**Comment by kugatsu765** [comment]
Unfortunatly we only use vite for our last app. We still have some apps build with webpack =(. 
Maybe a flag could be cool but i will not use script setup for my library to keep most power of TS =).

Thank you, have a good day
