### ISSUE TITLE
bundle inline dependencies

### ISSUE THREAD

**Issue by pi0** [unjs/mkdist#263]
### Describe the feature

Context: https://github.com/nuxt/module-builder/issues/445

> Sometimes, devDependencies are not published as they are only used locally. It would be a nice feature to inline the imports of those dependencies, so those do not have to be inlined manually (meaning, the import of the package is removed and the function is written directly into the file).

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
mkdist if file-by-file transformer (not bundler). an additional (rollup) entry needed for this. There are alternatives such as conditional exports. (https://github.com/nuxt/module-builder/issues/445#issuecomment-2541754677)

--

Closing issue as it lacks context (ie: why this might be needed? how commonly this is needed that makes sense to be a mkdist feature desipe it is not what it should do)

**Comment by danielroe** [comment]
Info as far as I know is that the devDependency @s1gr1d mentioned is not published to npm

(I think https://github.com/getsentry/sentry-javascript/pull/14680 is the PR in question)
