### ISSUE TITLE
Maybe provide options to define custom esbuild options?

### ISSUE THREAD

**Issue by uuau99999** [unjs/mkdist#39]
Hello, I want to use unbuild with mkdist builder to bundle my vue component library and publish them to npm. When using it in my vite project, it seems like vite will not do transform code inside node_modules and, however, my code are required to run in a web browser with chormium 70 and some syntaxs like optional chain may not be supported. I found that using unbuild with rollup builder supports custom rollupOptions and thus can specify custom esbuild options while mkdist does not support custom esbuild options. Maybe mkdist can provide options to define custom esbuild options? Thanks a lot!

Inside: https://github.com/unjs/mkdist/blob/main/src/loaders/js.ts#L33
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/6498327/163565664-6dd6e244-fc8c-4fa7-9f3c-678c65cfc8a0.png">

**Comment by chouchao** [comment]
same issue +1

**Comment by snowyu** [comment]
Yes,  I need pass the `keep-names`  option to esbuild too.

**Comment by uuau99999** [comment]
make a pr to support: #144
