### ISSUE TITLE
Improve import extension normalization

### ISSUE THREAD

**Issue by pi0** [unjs/mkdist#45]
mkdist uses a post-build transform to add explicit extensions ([src](https://github.com/unjs/mkdist/blob/bcff1496a3b41f59a4db868587c0b46ed0a0b8c8/src/make.ts#L90)) but this is not always working (eg with multi line imports) https://github.com/unjs/unbuild/issues/83. 

We shall migrate to [mlly.parseStaticImports](https://github.com/unjs/mlly#parsestaticimport).

**Comment by hieusmiths** [comment]
You mean that we will improve like this.

`{
            builder: "mkdist",
            input: "./src/common",
            name: "untils",
            outDir: "common",
            ext: "cjs",
            format: "cjs",
        },`
        
But after build, I see code built not imported with extension.

`var _other = require("../constants/other");`

So we need to update to: var _other = require("../constants/other.cjs");

Right man?

**Comment by pi0** [comment]
@hieusmiths Explicit .cjs extensions should be added in last version try upgrading. 

If rewrite is still not working, please share your source code snippet 🙏

**Comment by zoeyzhao19** [comment]
Facing with the same. @pi0 , but I am not understand why shall migrate to mlly.parseStaticImports. Is it possible to just improve the regx pattern 
```js
output.contents = output.contents!.replace(
    /(import|export)(.* from ["'])(.*)(["'])/g,
    (_, type, head, id, tail) => type + head + resolveId(output.path, id, esmResolveExtensions) + tail
  );
```
into
```js
output.contents = output.contents!.replace(
    /(import|export)([\s\S]* from ["'])(.*)(["'])/g,
    (_, type, head, id, tail) => type + head + resolveId(output.path, id, esmResolveExtensions) + tail
  );

```
It seems worked.

**Comment by alexgrozav** [comment]
I've created #120 to fix this. Would really appreciate it if we could merge and release the fix as the issue is creating broken builds without any warning for some people. 

**Note:** The `[\s\S]` solution above works in some cases, but will spill over to exported objects and functions.
